### ISSUE TITLE
Angular 2 или 4

### ISSUE THREAD

**Issue by theromis** [FriOne/angularjs-yandex-metrika#10]
Хотел узнать, нету ли планов выпустить код под subj?

**Comment by FriOne** [comment]
Были мысли об этом, но пока нет времени. В теории это должно быть не сложно, надо всего лишь перенести код. Есть репозиторий-сид для создания модулей под ангулар довольно неплохой, есть вероятность, что с помощью него сделаю, как будет время.

**Comment by FriOne** [comment]
@theromis сделал [первую версию](https://github.com/FriOne/ng-yandex-metrika). Было бы очень неплохо получить какой-то фидбэк или пулл реквест в случае, если что-то не работает, сам я пока не тестировал.

**Comment by theromis** [comment]
спасибо, на днях попробуем
