### ISSUE TITLE
Issue with "Session Replay"

### ISSUE THREAD

**Issue by vkupar** [FriOne/angularjs-yandex-metrika#12]
I'm recording user behavior with yandex metrica, but when yandex metrica shows for example landing page, at that time user is actually on another page. I mean it isn't loads pages correctly and I want to know this is plugin's problem or it's their problem with angular.js?

I used this plugin and after that their js code, but no one is not working properly.

Thank you

**Comment by FriOne** [comment]
"I used this plugin and after that their js code, but no one is not working properly." you already answered the question. This library only put script on a page. I guess they have some settings for SPA, but not sure.

**Comment by FriOne** [comment]
Hi, @vatex, I guess you ment Session Replay 2.0? Now I have issue on Angular2 repo here https://github.com/FriOne/ng-yandex-metrika/issues/5 . Not sure if I wanna make the same on AngularJS.
