### ISSUE TITLE
The package registered in bower is a fork

### ISSUE THREAD

**Issue by pballester** [FriOne/angularjs-yandex-metrika#8]
The package registered in bower.io is the fork https://github.com/GordonDrop/angularjs-yandex-metrika, not this one.

**Comment by FriOne** [comment]
@pballester I comment it in your PR.

**Comment by GordonDrop** [comment]
@FriOne Hi. I'm sorry i took your package name in bower registry. I'll unregister package at the end of week. I'll inform you about progress.
